# Use the official Python image from the Docker Hub
FROM python:3.12-slim

# Set the working directory in the container
WORKDIR /app

# Install pipenv
RUN pip install pipenv

# Copy Pipfile and Pipfile.lock into the container
COPY Pipfile Pipfile.lock ./

# Install the dependencies from Pipfile.lock
RUN pipenv --python 3.12
RUN pipenv install pytest
RUN pipenv install --system --deploy --dev

# Copy the rest of the application code into the container at /app
COPY . .

# Run pytest when the container starts
CMD ["pipenv", "run", "pytest", "--junitxml=report.xml"]

