name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -f Dockerfile.test . -t test
    
    - name: Build Docker image
      run: docker run -v ./:/app test 

    - name: Upload test report
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: report.xml

    - name: Report test results
      uses: dorny/test-reporter@v1
      with:
        report-path: report.xml
        reporter: junit
       
