name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build . -t fastapi-hello-world

    - name: Run Docker container
      run: |
        test=labas
        echo $test
        docker run -d -p 8181:80 fastapi-hello-world 
        curl -f http://127.0.0.1:8181 || exit 1
